function reportByGroup = getReportByGroup(groupIndex, nsfaReport, decayReport)
% Group anlysis results by experimental group.
% -------------------------------------------------------------------------
% Inputs: - groupIndex : groupIndex.xlsx imported by readIndex.m
%         - nsfaReport : generated by runNSFA2.m
%         - decayReport : generated by runFitDecay.m

%%
reportByGroup = table;

if ~exist("nsfaReport","var")
    nsfaReport = table;
end

if ~exist("decayReport","var")
    nsfaReport = table;
end

nGroup = height(groupIndex);
for g = 1:nGroup
    tempNSFA = table;   % temporary tables for transferring data
    tempDecay = table;  % temporary tables for transferring data
    gName = groupIndex.Properties.RowNames{g};
    nFile = height(groupIndex.files{g});
    for f = 1:nFile
        fName = groupIndex.files{g}.fileName{f};
        % copy NSFA results
        if ismember(fName,nsfaReport.Properties.RowNames)
            tempNSFA(fName,:) = nsfaReport(fName,:);
        end
        % copy decay results
        if ismember(fName,decayReport.Properties.RowNames)
            tempDecay(fName,:) = decayReport(fName,:);
        end
    end
    reportByGroup.NSFA{gName} = tempNSFA;
    reportByGroup.decay{gName} = tempDecay;
end

end
