function medCDF = plotGroupCDF(newFig,color,cdfFile,group,xAxisLabel)
%% Plot group CDF for bootstrap data of amplitude.

% Man Ho Wong, University of Pittsburgh.
% -------------------------------------------------------------------------
% Input: - newFig : set 1 to create new figure; 0 to plot on current figure
%        - color : RGB color code of the plot; e.g. [1 0 0] for red
%        - cdfFile : path to cdfParamsAndXyValues_<group name>.mat
%                    generated by fitGroupCDFExp.m or fitGroupCDFGamma.m
%        - group : group name of target group to plot
%        - xAxisLabel : x-xais label, e.g 'Amplitude (pA)'
% Output: - figure : CDF with median (solid line) and CI (shaded patch).
%         - medCDF : median CDF
%
% Example:
% plotEveryCDF(1, [0 0 1], 'path/to/cdfParamsAndXyValues_<group name>.mat', 'Amplitude (pA)')

%% Load CDF X-/Y-coordinate values

if ~isfile(cdfFile)
    fprintf(['''%s'' not found.\nPlease check if the path is correct' ...
             ' or run CDF fitting again.\n'],cdfFile);
    return;
end

load(cdfFile,'outcdf','x');

%% Plot cdf

if newFig == 1
    figure;
end
hold on;

% Show figure window even when the fucntion is called in live script
set(gcf,'Visible','on');

% plot median of cdf
medCDF = plot(x,outcdf(2,:),'DisplayName',string(group),'Color',color);

%plot CI of cdf as patches
valX = [x,fliplr(x)];
valY = [outcdf(3,:), fliplr(outcdf(1,:))];
ci = hggroup;   % Create a group for CI patches
                % (this group of objects can then be excluded from legend easily)
patch(valX,valY,1,'Parent',ci,'FaceColor',color,'EdgeColor','none');
alpha(.2);      % make patch transparent

ylim([0 1]);
xlabel(xAxisLabel);
ylabel('CDF');
legend(gca);       % Legend includes only direct children of current axis, no CI patch
legend("boxoff");  % Remove legend box
hold off;

fprintf(['Done! To continue plotting on current figure:\n' ...
    '- Make sure it is the only figure or the last selected window.\n' ...
    '- Repeat the above step with ''Plot on current figure''.\n']);

end


